In [1]:
import numpy as np
from scipy.stats import binom

In [2]:
# Set up input variables
spot = 41.0
strike = 40.0
rate = 0.08
sigma = 0.30
expiry = 1.0
steps = 3
nodes = steps + 1
h = expiry / steps


In [4]:
# the Call payoff
def call_payoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

In [5]:
whos

Variable      Type         Data/Info
------------------------------------
binom         binom_gen    <scipy.stats._discrete_di<...>ct at 0x000000FA3DAFACF8>
call_payoff   function     <function call_payoff at 0x000000FA3D9E5C80>
expiry        float        1.0
h             float        0.3333333333333333
nodes         int          4
np            module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
rate          float        0.08
sigma         float        0.3
spot          float        41.0
steps         int          3
strike        float        40.0


In [6]:
# u, d, pstar
u = np.exp(rate * h + sigma * np.sqrt(h))
d = np.exp(rate * h - sigma * np.sqrt(h))
pstar = (np.exp(rate * h) - d) / (u - d)

In [7]:
u

1.2212461201543867

In [8]:
d

0.86369255373382114

In [9]:
pstar

0.45680665920961433

In [10]:
binom.pmf?

In [38]:
# the main loop
total = 0.0

spotT = np.zeros((nodes))
callT = np.zeros((nodes))
probT = np.zeros((nodes))

disc = np.exp(-rate * expiry)

for i in range(nodes):
    spotT[i] = spot * (u ** (steps - i)) * (d ** (i))
    callT[i] = call_payoff(spotT[i], strike)
    probT[i] = binom.pmf(steps - i, steps, pstar)
    #print(spotT, callT, probT)
    total += callT[i] * probT
    
#call_price = np.exp(-rate * expiry) * sum 
#print("The Call Price is: {0:0.3f}".format(call_price))

In [39]:
# the main loop
total = 0.0
disc = np.exp(-rate * expiry)

for i in range(nodes):
    spotT = spot * (u ** (steps - i)) * (d ** (i))
    callT = call_payoff(spotT, strike)
    probT = binom.pmf(steps - i, steps, pstar)
    #print(spotT, callT, probT)
    total += callT * probT
    
#call_price = np.exp(-rate * expiry) * sum 
#print("The Call Price is: {0:0.3f}".format(call_price))

In [26]:
spotT

array([ 74.6781323 ,  52.81404438,  37.3512727 ,  26.41565494])

In [27]:
callT

array([ 34.6781323 ,  12.81404438,   0.        ,   0.        ])

In [28]:
probT

array([ 0.09532291,  0.34004825,  0.40435476,  0.16027409])

In [30]:
price = callT * probT

In [36]:
price.sum()

7.6630137565724787

In [33]:
disc

0.92311634638663576

In [41]:
total * disc

7.0738532612777147

In [43]:
# This is your homework portion!
def EuropeanCallBinomial(stuff):
    pass