# Naive Monte Carlo in a Black-Scholes Economy


$$
S_{T} = S_{0} \exp{\left((r - \delta  + \frac{1}{2} \sigma^{2}) T + \sigma \sqrt{T} Z \right)}
$$

In [2]:
import numpy as np

In [3]:
z = np.random.normal(size = 100)

In [4]:
z

array([ 0.34067867, -0.71278895,  0.89753068,  0.74079037,  0.52681485,
        0.69729953, -0.76018215,  0.08113456, -0.98383365,  0.07898747,
       -0.03234235, -1.12524522,  0.13790314,  1.91862144,  1.287956  ,
       -0.91061481,  0.12927475, -2.92755517, -0.95369731,  1.38755157,
        0.08769175, -0.998732  ,  0.66286841, -0.56586878,  1.23229544,
        0.46135349, -1.3928623 , -1.78900856, -1.19723727,  1.43577193,
        0.7562182 , -1.29758931, -1.02121032, -0.78630597, -0.31261907,
        0.09194849,  0.01137565,  0.69021164, -0.26340716,  1.57215614,
       -0.04685436, -0.51408477,  0.88997809, -0.13717274,  0.74622856,
        0.89106649, -0.68217428, -0.00372201, -3.1166331 , -1.19087643,
       -1.3957511 , -2.40329173,  0.35696525,  0.68980898, -0.17455616,
       -0.83370642, -1.36289085,  1.34034446,  0.9229708 ,  0.55464605,
       -1.82336334,  0.20860162,  0.12556506, -0.13924194,  0.21003312,
        1.08065628,  0.98473177, -0.1979559 ,  0.13376882, -0.33

## Set Up Parameters

In [5]:
S = 41.0
K = 40.0
r = 0.08
v = 0.30
T = 1.0
q = 0.0


In [6]:
M = 1000000
spot_t = np.empty((M,))


In [7]:
nudt = (r - q - 0.5 * v * v) * T
sigdt = v * np.sqrt(T)
z = np.random.normal(size=(M,))

In [8]:
#for i in range(M):
#    spot_t[i] = S * np.exp(nudt + sigdt * z[i])

In [9]:
spot_t = S * np.exp(nudt + sigdt * z)

In [10]:
spot_t[:10]

array([ 27.41500167,  46.75699694,  56.9792174 ,  31.89235976,
        75.75444511,  49.67393605,  42.88691931,  40.36975374,
        48.98280929,  42.09394923])

In [11]:
def CallPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)


def PutPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

In [12]:
call_t = CallPayoff(spot_t, K)

In [13]:
call_t[:10]

array([  0.        ,   6.75699694,  16.9792174 ,   0.        ,
        35.75444511,   9.67393605,   2.88691931,   0.36975374,
         8.98280929,   2.09394923])

In [14]:
bob = call_t.mean()

In [15]:
bob

7.544198724585331

In [16]:
callPrc = np.exp(-r * T) * bob

In [17]:
callPrc

6.9641731630539283

In [18]:
put_t = PutPayoff(spot_t, K)

In [19]:
put_t[:10]

array([ 12.58499833,   0.        ,   0.        ,   8.10764024,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ])

In [20]:
putPrc = np.exp(-r * T) * put_t.mean()

In [21]:
putPrc

2.884570352778089

## Simulating Paths

In [33]:
reps = 3
steps = 30
path = np.zeros((reps,steps))

In [34]:
path
path[:,0] = S
path

array([[ 41.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 41.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 41.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [35]:
dt = T / steps
nudt = (r - q - 0.5 * v * v) * dt
sigdt = v * np.sqrt(dt)

In [36]:

for i in range(reps):
    z = np.random.normal(size=steps)
    for j in range(1, steps):
        path[i,j] = path[i,j-1] * np.exp(nudt + sigdt * z[j])
        
path

array([[ 41.        ,  38.50200983,  37.64461333,  36.49759545,
         34.92330909,  32.64319169,  31.27213927,  31.0622597 ,
         29.5654966 ,  29.04677181,  28.21154314,  28.87336692,
         27.30402677,  28.36525528,  27.20874623,  28.56565423,
         28.60765072,  29.20132739,  29.02210066,  30.09669557,
         30.57028076,  32.17129786,  31.78141259,  29.56792588,
         30.82731248,  31.79354298,  32.89140809,  33.35785143,
         32.02739144,  35.97998698],
       [ 41.        ,  46.63729406,  43.2971757 ,  42.87800314,
         40.79433057,  45.45437434,  42.77199315,  41.05122388,
         39.21732263,  41.15117712,  39.89917708,  45.35360398,
         45.88622652,  41.65832426,  41.18360985,  45.21651123,
         43.51031663,  46.76949013,  47.58840871,  48.6133947 ,
         51.67283322,  49.11405398,  50.28454034,  54.67213301,
         63.38081996,  69.49015697,  69.08727333,  77.44432394,
         69.17569758,  73.24485918],
       [ 41.        ,  42.7883