## __McDonald Chapter 10: The Single-Period Binomial Option Pricing Model__

### Market Data Inputs

In [4]:
import numpy as np

In [28]:
spot = 100.0
strike = 105.0
rate = 0.08
expiry = 0.5
delta = 0.0
n = 1
h = expiry / n

### Model Parameters

In [29]:
u = 1.3
d = 0.8

In [30]:
whos

Variable      Type        Data/Info
-----------------------------------
B             float64     -36.92465385546543
C0            float64     13.07534614453457
Cd            float64     0.0
Cu            float64     25.0
D             float64     0.5
Pd            float64     25.0
Pu            float64     0.0
call_payoff   function    <function call_payoff at 0x000001C6ADB34040>
d             float       0.8
delta         float       0.0
expiry        float       0.5
h             float       0.5
n             int         1
np            module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
put_payoff    function    <function put_payoff at 0x000001C6ADB340D0>
rate          float       0.08
spot          float       100.0
strike        float       105.0
tree          ndarray     2: 2 elems, type `float64`, 16 bytes
u             float       1.3


### Option Payoff Functions

In [31]:
def call_payoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

In [32]:
def put_payoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

### Stock Price Tree

In [33]:
n = 1
tree = np.zeros((n+1,))

In [34]:
tree

array([0., 0.])

In [35]:
tree[0] = u * spot
tree[1] = d * spot

In [36]:
tree

array([130.,  80.])

In [37]:
Cu, Cd = call_payoff(tree, strike)

In [38]:
Cu

25.0

In [39]:
Cd

0.0

In [40]:
Pu, Pd = put_payoff(tree, strike)

In [41]:
Pu

0.0

In [42]:
Pd

25.0

### The Binomial Model $\Delta$ and $B$

In [49]:
Dc = np.exp(-delta * h) * ((Cu - Cd) / (spot * (u - d)))

In [50]:
D

0.5

In [51]:
Bc = np.exp(-rate * h) * ((u*Cd - d*Cu) / (u - d))

In [52]:
B

-38.431577566092926

### The Single-Period Binomial Call Price

In [53]:
C0 = Dc * spot + Bc

In [54]:
C0

11.568422433907074

### The Single-Period Binomial Put Option

In [55]:
Dp = np.exp(-delta * h) * ((Pu - Pd) / (spot * (u - d)))

In [56]:
Dp

-0.5

In [57]:
Bp = np.exp(-rate * h) * ((u*Pd - d*Pu) / (u - d))

In [58]:
P0 = Dp*spot + Bp

In [59]:
P0

12.451313544901005

### Check This Against Put-Call Parity (Chapter 09)

#### Problem 10.1 in Python

##### __(a)__

In [60]:
spot = 100.0
strike = 105.0
rate = 0.08
expiry = 0.5
delta = 0.0

In [61]:
u = 1.3
d = 0.8

In [62]:
tree = np.zeros((n+1,))

In [63]:
tree[0] = u * spot

In [64]:
tree[1] = d * spot

In [65]:
tree

array([130.,  80.])

In [67]:
Cu, Cd = call_payoff(tree, strike)

In [68]:
Pu, Pd = put_payoff(tree, strike)

In [69]:
Dc = np.exp(-delta * h) * ((Cu - Cd) / (spot * (u - d)))

In [70]:
Bc = np.exp(-rate * h) * ((u*Cd - d*Cu) / (u - d))

In [71]:
C0 = Dc * spot + Bc

In [72]:
C0

11.568422433907074

In [82]:
print(f"The call option premium is: ${C0 : 0.3f}")
print(f"The call Delta is: {Dc : 0.3f}")
print(f"The call B is: {Bc : 0.3f}")

The call option premium is: $ 11.568
The call Delta is:  0.500
The call B is: -38.432


##### __(b)__

In [83]:
Dp = np.exp(-delta * h) * ((Pu - Pd) / (spot * (u - d)))

In [85]:
Bp = np.exp(-rate * h) * ((u*Pd - d*Pu) / (u - d))

In [86]:
P0 = Dp * spot + Bp

In [87]:
print(f"The put option premium is: ${P0 : 0.3f}")
print(f"The put Delta is: {Dp : 0.3f}")
print(f"The put B is: {Bp : 0.3f}")

The put option premium is: $ 12.451
The put Delta is: -0.500
The put B is:  62.451


#### Some Notes on the Steps for the Single-Perio Binomial Model

* __Step 0:__ Take all market data ($S_{0}$, $K$, $r$, $\delta$, $T$) and other bits ($u$, $d$) as given
* __Step 1:__ Using $u$ and $d$ build the stock price tree forward: get $u \times S$ and $d \times S$
* __Step 2:__ Apply the boundary condition: use the call or put payoff function given the stock price tree: $C_{u}$ and $C_{d}$ (also $P_{u}$ and $P_{d}$)
* __Step 3:__ 
    - __a__ for the No-arbitrage model solve for $\Delta$ and $B$ (for the call or put respectively)
    - __b__ for the risk-neutral model solve for $p^{\ast}$
* __Step 4:__ Use the data in Step 4 to solve for $C_{0}$ and/or $P_{0}$